CREATE TABLE `rows`(
    rows_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'rows_id',
    puid bigint(11) NULL COMMENT '10002',
    data_id bigint(100) NULL COMMENT 'data_id',
    shop_id bigint(11) NULL COMMENT '387',
    shop_name varchar(100) NULL COMMENT '演示店铺-50764',
    marketplace_id varchar(100) NULL COMMENT 'A1F83G8C2ARO7P',
    marketplace varchar(100) NULL COMMENT 'UK',
    marketplace_c_n varchar(100) NULL COMMENT '英国',
    group_id varchar(100) NULL COMMENT 'SRsHIZ4JB38nECy3pLY59rgXPDcQ6q-5zwLBKpAPOPU',
    processing_status varchar(100) NULL COMMENT 'Open',
    processing_status_name varchar(100) NULL COMMENT '未结算',
    fund_transfer_date varchar(100) NULL COMMENT 'null',
    fund_transfer_date_p_s_t varchar(100) NULL COMMENT 'null',
    fund_transfer_status varchar(100) NULL COMMENT 'null',
    fund_transfer_status_name varchar(100) NULL COMMENT 'null',
    original_total_currency_code varchar(100) NULL COMMENT 'GBP',
    original_total_currency_amount bigint(11) NULL COMMENT '0',
    converted_total_currency_code varchar(100) NULL COMMENT 'USD',
    converted_total_currency_amount bigint(11) NULL COMMENT '0',
    trace_id varchar(100) NULL COMMENT 'null',
    account_tail varchar(100) NULL COMMENT '1234',
    beginning_balance_currency_code varchar(100) NULL COMMENT 'GBP',
    beginning_balance_currency_amount bigint(11) NULL COMMENT '-25',
    financial_event_group_start varchar(100) NULL COMMENT '2021-05-26 20:18:56',
    financial_event_group_start_p_s_t varchar(100) NULL COMMENT '2021-05-26 20:18:56',
    financial_event_group_end varchar(100) NULL COMMENT 'null',
    financial_event_group_end_p_s_t varchar(100) NULL COMMENT 'null',
    amount bigint(11) NULL COMMENT '0',
    amount_currency varchar(100) NULL COMMENT 'GBP',
    transfer_amount bigint(11) NULL COMMENT '0',
    transfer_amount_currency varchar(100) NULL COMMENT 'GBP',
    reserve_debit_amount bigint(11) NULL COMMENT '0',
    reserve_debit_currency varchar(100) NULL COMMENT 'null',
    remark varchar(100) NULL COMMENT '回款记录备注',
    PRIMARY KEY (`rows_id`) USING BTREE,
    KEY `data_id` (`data_id`),
    CONSTRAINT `rows_fk_data_id` FOREIGN KEY (`data_id`) REFERENCES `data` (`data_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='rows';
CREATE TABLE `data`(
    data_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'data_id',
    total_amount varchar(100) NULL COMMENT '2592.27',
    root_id bigint(100) NULL COMMENT 'root_id',
    total_amount_currency varchar(100) NULL COMMENT 'USD',
    total_transfer_amount varchar(100) NULL COMMENT '6160.81',
    total_transfer_amount_currency varchar(100) NULL COMMENT 'USD',
    PRIMARY KEY (`data_id`) USING BTREE,
    KEY `root_id` (`root_id`),
    CONSTRAINT `data_fk_root_id` FOREIGN KEY (`root_id`) REFERENCES `root` (`root_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='data';
