CREATE TABLE `data`(
    data_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'data_id',
    month varchar(100) NULL COMMENT 'null',
    data_id bigint(100) NULL COMMENT 'data_id',
    shop_id varchar(100) NULL COMMENT 'null',
    shop_name varchar(100) NULL COMMENT 'null',
    marketplace_id varchar(100) NULL COMMENT 'null',
    marketplace varchar(100) NULL COMMENT 'null',
    sum_sales_num bigint(11) NULL COMMENT '348',
    fba_sales_num bigint(11) NULL COMMENT '335',
    fbm_sales_num bigint(11) NULL COMMENT '13',
    fba_reissue_num bigint(11) NULL COMMENT '4',
    multi_channel_num bigint(11) NULL COMMENT '20',
    refund_num bigint(11) NULL COMMENT '30',
    return_num bigint(11) NULL COMMENT '1',
    compensation_num bigint(11) NULL COMMENT '7',
    disposed_num bigint(11) NULL COMMENT '0',
    removal_num bigint(11) NULL COMMENT '0',
    sum_order_sales varchar(100) NULL COMMENT '9885.94',
    product_sales varchar(100) NULL COMMENT '11849.03',
    shipping_credits varchar(100) NULL COMMENT '228.71',
    promotional_rebates varchar(100) NULL COMMENT '-941.44',
    refund varchar(100) NULL COMMENT '-1250.36',
    compensation varchar(100) NULL COMMENT '171.43',
    adj_compensation varchar(100) NULL COMMENT '171.43',
    sum_order_fee varchar(100) NULL COMMENT '-3153.91',
    sale_order_fee varchar(100) NULL COMMENT '-3171.86',
    sale_selling_fee varchar(100) NULL COMMENT '-1642.41',
    sale_fba_fee varchar(100) NULL COMMENT '-1470.54',
    sale_fbm_fee varchar(100) NULL COMMENT '-58.91',
    sale_other_fee varchar(100) NULL COMMENT '0.00',
    multi_channel_order_fee varchar(100) NULL COMMENT '-115.00',
    mc_fba_ship_fee varchar(100) NULL COMMENT '-115.00',
    refund_order_fees varchar(100) NULL COMMENT '132.95',
    refund_selling_fee varchar(100) NULL COMMENT '128.51',
    refund_fba_fee varchar(100) NULL COMMENT '4.44',
    refund_other_fee varchar(100) NULL COMMENT '0.00',
    sum_fba_storage_fee varchar(100) NULL COMMENT '-51.58',
    sum_shop_fba_storage_fee varchar(100) NULL COMMENT 'null',
    fba_storage_fee varchar(100) NULL COMMENT '-49.84',
    fba_storage_fee_diff varchar(100) NULL COMMENT 'null',
    fba_long_storage_fee varchar(100) NULL COMMENT '0.00',
    sum_shop_fba_storage_other_fee varchar(100) NULL COMMENT 'null',
    fba_adjustment_fee varchar(100) NULL COMMENT '0.00',
    fba_disposal_fee varchar(100) NULL COMMENT '-1.74',
    fba_removal_fee varchar(100) NULL COMMENT '0.00',
    fba_return_fee varchar(100) NULL COMMENT '0.00',
    fba_ship_fee varchar(100) NULL COMMENT '0.00',
    fba_storage_other_fee varchar(100) NULL COMMENT '0.00',
    fba_inventory_placement_fee varchar(100) NULL COMMENT '0.00',
    sum_cpc_cost varchar(100) NULL COMMENT '-1602.94',
    cpc_cost varchar(100) NULL COMMENT '-1602.94',
    cpc_cost_diff varchar(100) NULL COMMENT 'null',
    sum_promote_fee varchar(100) NULL COMMENT '-502.88',
    ld_promote_fee varchar(100) NULL COMMENT '-450.00',
    coupons_promote_fee varchar(100) NULL COMMENT '-52.88',
    erp_promote_fee varchar(100) NULL COMMENT '0.00',
    sum_tax varchar(100) NULL COMMENT '32.46',
    tax varchar(100) NULL COMMENT '32.46',
    sum_product_cost_fee varchar(100) NULL COMMENT '-7819.56',
    sum_purchase_fee varchar(100) NULL COMMENT 'null',
    sum_head_trip_fee varchar(100) NULL COMMENT 'null',
    sale_pc_fee varchar(100) NULL COMMENT '-8358.42',
    purchase_pc_fee varchar(100) NULL COMMENT '-6688.48',
    head_trip_pc_fee varchar(100) NULL COMMENT '-1669.94',
    disposed_pc_fee varchar(100) NULL COMMENT '0.00',
    purchase_dpc_fee varchar(100) NULL COMMENT '0.00',
    head_trip_dpc_fee varchar(100) NULL COMMENT '0.00',
    return_pc_fee varchar(100) NULL COMMENT '-16.77',
    purchase_rtpc_fee varchar(100) NULL COMMENT '-8.30',
    head_trip_rtpc_fee varchar(100) NULL COMMENT '-8.47',
    adj_compensation_pc_fee varchar(100) NULL COMMENT '-193.34',
    purchase_acpc_fee varchar(100) NULL COMMENT '-161.43',
    head_trip_acpc_fee varchar(100) NULL COMMENT '-31.91',
    multi_channel_pc_fee varchar(100) NULL COMMENT '683.76',
    purchase_mcpc_fee varchar(100) NULL COMMENT '24.30',
    head_trip_mcpc_fee varchar(100) NULL COMMENT '659.46',
    reissue_pc_fee varchar(100) NULL COMMENT '65.21',
    purchase_rpc_fee varchar(100) NULL COMMENT '14.47',
    head_trip_rpc_fee varchar(100) NULL COMMENT '50.74',
    sum_batch_product_cost_fee varchar(100) NULL COMMENT 'null',
    sum_batch_purchase_fee varchar(100) NULL COMMENT 'null',
    sum_batch_head_trip_fee varchar(100) NULL COMMENT 'null',
    sum_batch_purchase_other_fee varchar(100) NULL COMMENT 'null',
    sum_batch_head_trip_other_fee varchar(100) NULL COMMENT 'null',
    batch_sale_pc_fee varchar(100) NULL COMMENT 'null',
    batch_purchase_pc_fee varchar(100) NULL COMMENT 'null',
    batch_trip_pc_fee varchar(100) NULL COMMENT 'null',
    batch_customer_returns_pc_fee varchar(100) NULL COMMENT 'null',
    batch_purchase_crpc_fee varchar(100) NULL COMMENT 'null',
    batch_trip_crpc_fee varchar(100) NULL COMMENT 'null',
    batch_adjustments_pc_fee varchar(100) NULL COMMENT 'null',
    batch_purchase_apc_fee varchar(100) NULL COMMENT 'null',
    batch_trip_apc_fee varchar(100) NULL COMMENT 'null',
    batch_vendor_returns_pc_fee varchar(100) NULL COMMENT 'null',
    batch_purchase_vrpc_fee varchar(100) NULL COMMENT 'null',
    batch_trip_vrpc_fee varchar(100) NULL COMMENT 'null',
    batch_difference_pc_fee varchar(100) NULL COMMENT 'null',
    batch_purchase_dfpc_fee varchar(100) NULL COMMENT 'null',
    batch_trip_dfpc_fee varchar(100) NULL COMMENT 'null',
    sum_other_fee varchar(100) NULL COMMENT '119.28',
    subscription_fee varchar(100) NULL COMMENT '-284.88',
    other_fee varchar(100) NULL COMMENT '404.16',
    sum_customize_fee varchar(100) NULL COMMENT '-513.67',
    evaluation_fee varchar(100) NULL COMMENT '0.00',
    evaluation_capital varchar(100) NULL COMMENT '0.00',
    evaluation_commission varchar(100) NULL COMMENT '0.00',
    shop_other_fee varchar(100) NULL COMMENT '0.00',
    asin_other_fee varchar(100) NULL COMMENT '0.00',
    fixed_fee varchar(100) NULL COMMENT '-513.67',
    gross_profit varchar(100) NULL COMMENT '-3435.43',
    gross_profit_rate varchar(100) NULL COMMENT '-28.99',
    roi varchar(100) NULL COMMENT '-25.46',
    ori_currency varchar(100) NULL COMMENT 'null',
    currency varchar(100) NULL COMMENT 'USD',
    shop_other_fees varchar(100) NULL COMMENT 'null',
    bad_data_items varchar(100) NULL COMMENT 'null',
    PRIMARY KEY (`data_id`) USING BTREE,
    KEY `data_id` (`data_id`),
    CONSTRAINT `data_fk_data_id` FOREIGN KEY (`data_id`) REFERENCES `data` (`data_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='data';

CREATE TABLE `asin_other_fees`(
    asin_other_fees_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'asin_other_fees_id',
    create_time varchar(100) NULL COMMENT '2021-04-20 21:06:02',
    data_id bigint(100) NULL COMMENT 'data_id',
    update_time varchar(100) NULL COMMENT '2021-04-30 18:25:06',
    id bigint(11) NULL COMMENT '90',
    puid bigint(11) NULL COMMENT '10002',
    shop_id bigint(11) NULL COMMENT '605',
    month varchar(100) NULL COMMENT '202103',
    asin varchar(100) NULL COMMENT 'SDA-26074E9A7F',
    type bigint(11) NULL COMMENT '1',
    fee bigint(11) NULL COMMENT '0',
    currency varchar(100) NULL COMMENT 'USD',
    type_name varchar(100) NULL COMMENT 'null',
    PRIMARY KEY (`asin_other_fees_id`) USING BTREE,
    KEY `data_id` (`data_id`),
    CONSTRAINT `asin_other_fees_fk_data_id` FOREIGN KEY (`data_id`) REFERENCES `data` (`data_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='asin_other_fees';
CREATE TABLE `shop_fee_types`(
    shop_fee_types_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'shop_fee_types_id',
    create_time varchar(100) NULL COMMENT 'null',
    data_id bigint(100) NULL COMMENT 'data_id',
    update_time varchar(100) NULL COMMENT 'null',
    id bigint(11) NULL COMMENT '0',
    puid varchar(100) NULL COMMENT 'null',
    dimension varchar(100) NULL COMMENT 'null',
    type_name varchar(100) NULL COMMENT '其他费',
    PRIMARY KEY (`shop_fee_types_id`) USING BTREE,
    KEY `data_id` (`data_id`),
    CONSTRAINT `shop_fee_types_fk_data_id` FOREIGN KEY (`data_id`) REFERENCES `data` (`data_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='shop_fee_types';
CREATE TABLE `asin_fee_types`(
    asin_fee_types_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'asin_fee_types_id',
    create_time varchar(100) NULL COMMENT 'null',
    data_id bigint(100) NULL COMMENT 'data_id',
    update_time varchar(100) NULL COMMENT 'null',
    id bigint(11) NULL COMMENT '1',
    puid varchar(100) NULL COMMENT 'null',
    dimension varchar(100) NULL COMMENT 'null',
    type_name varchar(100) NULL COMMENT '其他费',
    PRIMARY KEY (`asin_fee_types_id`) USING BTREE,
    KEY `data_id` (`data_id`),
    CONSTRAINT `asin_fee_types_fk_data_id` FOREIGN KEY (`data_id`) REFERENCES `data` (`data_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='asin_fee_types';



-- 商品成本
CREATE TABLE `data`(
    data_id bigint(100) NOT NULL AUTO_INCREMENT COMMENT 'data_id',
    id varchar(100) NULL COMMENT 'null',
    root_id bigint(100) NULL COMMENT 'root_id',
    code varchar(100) NULL COMMENT 'SUM_TAX',
    title varchar(100) NULL COMMENT '税费',
    sub_item varchar(100) NULL COMMENT 'null',
    is_system bigint(11) NULL COMMENT '2',
    profit_type bigint(11) NULL COMMENT '2',
    is_active bigint(11) NULL COMMENT '1',
    cost_type bigint(11) NULL COMMENT '0',
    sort_num varchar(100) NULL COMMENT 'null',
    PRIMARY KEY (`data_id`) USING BTREE,
    KEY `root_id` (`root_id`),
    CONSTRAINT `data_fk_root_id` FOREIGN KEY (`root_id`) REFERENCES `root` (`root_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='data';
